class CountryConfig
  class << self
    def config
      {
        AL: {
          name: 'Albania',
          code: 'AL',
          bban_format: '8n,16c',
          iban_length: 28,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 11],
          branch_code_regex: '\d{4}',
          national_checksum: [11, 12],
          national_checksum_regex: '\d{1}',
          account_number: [12, 28],
          account_number_regex: '[a-zA-Z0-9]{16}',
          regex: 'AL\d\d\d{8}[a-zA-Z0-9]{16}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        AD: {
          name: 'Andorra',
          code: 'AD',
          bban_format: '8n,12c',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          account_number: [12, 24],
          account_number_regex: '[a-zA-Z0-9]{12}',
          regex: 'AD\d\d\d{8}[a-zA-Z0-9]{12}',
          parts: %w[bank_code branch_code account_number],
          },
        AT: {
          name: 'Austria',
          code: 'AT',
          bban_format: '16n',
          iban_length: 20,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          account_number: [9, 20],
          account_number_regex: '\d{11}',
          regex: 'AT\d\d\d{16}',
          parts: %w[bank_code account_number],
          },
        AZ: {
          name: 'Azerbaijan',
          code: 'AZ',
          bban_format: '4c,20n',
          iban_length: 28,
          bank_code: [4, 8],
          bank_code_regex: '[a-zA-Z0-9]{4}',
          account_number: [8, 28],
          account_number_regex: '\d{20}',
          regex: 'AZ\d\d[a-zA-Z0-9]{4}\d{20}',
          parts: %w[bank_code account_number],
          },
        BH: {
          name: 'Bahrain',
          code: 'BH',
          bban_format: '4a,14c',
          iban_length: 22,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 22],
          account_number_regex: '[a-zA-Z0-9]{14}',
          regex: 'BH\d\d[A-Z]{4}[a-zA-Z0-9]{14}',
          parts: %w[bank_code account_number],
          },
        BY: {
          name: 'Belarus',
          code: 'BY',
          bban_format: '4c,4n,16c',
          iban_length: 28,
          bank_code: [4, 8],
          bank_code_regex: '[a-zA-Z0-9]{4}',
          account_number: [12, 28],
          account_number_regex: '[a-zA-Z0-9]{16}',
          balance_account_number: [8, 12],
          balance_account_number_regex: '\d{4}',
          regex: 'BY\d\d[a-zA-Z0-9]{4}\d{4}[a-zA-Z0-9]{16}',
          parts: %w[bank_code account_number balance_account_number],
          },
        BE: {
          name: 'Belgium',
          code: 'BE',
          bban_format: '12n',
          iban_length: 16,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          national_checksum: [14, 16],
          national_checksum_regex: '\d{2}',
          account_number: [7, 14],
          account_number_regex: '\d{7}',
          regex: 'BE\d\d\d{12}',
          parts: %w[bank_code checksum account_number],
          },
        BA: {
          name: 'Bosnia and Herzegovina',
          code: 'BA',
          bban_format: '16n',
          iban_length: 20,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 10],
          branch_code_regex: '\d{3}',
          national_checksum: [18, 20],
          national_checksum_regex: '\d{2}',
          account_number: [10, 18],
          account_number_regex: '\d{8}',
          regex: 'BA\d\d\d{16}',
          parts: %w[bank_code branch_code checksum account_number],
          const_global_checksum: '39',
          },
        BR: {
          name: 'Brazil',
          code: 'BR',
          bban_format: '23n,1a,1c',
          iban_length: 29,
          bank_code: [4, 12],
          bank_code_regex: '\d{8}',
          branch_code: [12, 17],
          branch_code_regex: '\d{5}',
          account_number: [17, 27],
          account_number_regex: '\d{10}',
          account_type: [27, 28],
          account_type_regex: '[A-Z]{1}',
          owner_account_number: [28, 29],
          owner_account_number_regex: '[a-zA-Z0-9]{1}',
          regex: 'BR\d\d\d{23}[A-Z]{1}[a-zA-Z0-9]{1}',
          parts: %w[bank_code branch_code account_number account_type owner_account_number],
          },
        BG: {
          name: 'Bulgaria',
          code: 'BG',
          bban_format: '4a,6n,8c',
          iban_length: 22,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          account_number: [14, 22],
          account_number_regex: '[a-zA-Z0-9]{8}',
          account_type: [12, 14],
          account_type_regex: '\d{2}',
          regex: 'BG\d\d[A-Z]{4}\d{6}[a-zA-Z0-9]{8}',
          parts: %w[bank_code branch_code account_number account_type],
          },
        CR: {
          name: 'Costa Rica',
          code: 'CR',
          bban_format: '18n',
          iban_length: 22,
          bank_code: [5, 8],
          bank_code_regex: '\d{3}',
          account_number: [8, 22],
          account_number_regex: '\d{14}',
          zero: [4, 5],
          zero_regex: '\d{1}',
          regex: 'CR\d\d\d{18}',
          parts: %w[bank_code account_number],
          },
        HR: {
          name: 'Croatia',
          code: 'HR',
          bban_format: '17n',
          iban_length: 21,
          bank_code: [4, 11],
          bank_code_regex: '\d{7}',
          account_number: [11, 21],
          account_number_regex: '\d{10}',
          regex: 'HR\d\d\d{17}',
          parts: %w[bank_code account_number],
          },
        CY: {
          name: 'Cyprus',
          code: 'CY',
          bban_format: '8n,16c',
          iban_length: 28,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 12],
          branch_code_regex: '\d{5}',
          account_number: [12, 28],
          account_number_regex: '[a-zA-Z0-9]{16}',
          regex: 'CY\d\d\d{8}[a-zA-Z0-9]{16}',
          parts: %w[bank_code branch_code account_number],
          },
        CZ: {
          name: 'Czech Republic',
          code: 'CZ',
          bban_format: '20n',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [12, 14],
          branch_code_regex: '\d{2}',
          account_number: [14, 24],
          account_number_regex: '\d{10}',
          account_prefix: [8, 12],
          account_prefix_regex: '\d{4}',
          regex: 'CZ\d\d\d{20}',
          parts: %w[bank_code branch_code account_number account_prefix],
          },
        DK: {
          name: 'Denmark',
          code: 'DK',
          bban_format: '14n',
          iban_length: 18,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          national_checksum: [17, 18],
          national_checksum_regex: '\d{1}',
          account_number: [8, 17],
          account_number_regex: '\d{9}',
          regex: 'DK\d\d\d{14}',
          parts: %w[bank_code checksum account_number],
          },
        DO: {
          name: 'Dominican Republic',
          code: 'DO',
          bban_format: '4a,20n',
          iban_length: 28,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 28],
          account_number_regex: '\d{20}',
          regex: 'DO\d\d[A-Z]{4}\d{20}',
          parts: %w[bank_code account_number],
          },
        TL: {
          name: 'East Timor',
          code: 'TL',
          bban_format: '19n',
          iban_length: 23,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          national_checksum: [21, 23],
          national_checksum_regex: '\d{2}',
          account_number: [7, 21],
          account_number_regex: '\d{14}',
          regex: 'TL\d\d\d{19}',
          parts: %w[bank_code checksum account_number],
          const_global_checksum: '38',
          },
        EG: {
          name: 'Egypt',
          code: 'EG',
          bban_format: '25n',
          iban_length: 29,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          account_number: [12, 29],
          account_number_regex: '\d{17}',
          regex: 'EG\d\d\d{25}',
          parts: %w[bank_code branch_code account_number],
          },
        SV: {
          name: 'El Salvador',
          code: 'SV',
          bban_format: '4a,20n',
          iban_length: 28,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 28],
          account_number_regex: '\d{20}',
          regex: 'SV\d\d[A-Z]{4}\d{20}',
          parts: %w[bank_code account_number],
          },
        EE: {
          name: 'Estonia',
          code: 'EE',
          bban_format: '16n',
          iban_length: 20,
          bank_code: [4, 6],
          bank_code_regex: '\d{2}',
          branch_code: [6, 8],
          branch_code_regex: '\d{2}',
          national_checksum: [19, 20],
          national_checksum_regex: '\d{1}',
          account_number: [8, 19],
          account_number_regex: '\d{11}',
          regex: 'EE\d\d\d{16}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        FO: {
          name: 'Faroe Islands',
          code: 'FO',
          bban_format: '14n',
          iban_length: 18,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          national_checksum: [17, 18],
          national_checksum_regex: '\d{1}',
          account_number: [8, 17],
          account_number_regex: '\d{9}',
          regex: 'FO\d\d\d{14}',
          parts: %w[bank_code checksum account_number],
          },
        FI: {
          name: 'Finland',
          code: 'FI',
          bban_format: '14n',
          iban_length: 18,
          bank_code: [4, 10],
          bank_code_regex: '\d{6}',
          national_checksum: [17, 18],
          national_checksum_regex: '\d{1}',
          account_number: [10, 17],
          account_number_regex: '\d{7}',
          regex: 'FI\d\d\d{14}',
          parts: %w[bank_code checksum account_number],
          },
        FR: {
          name: 'France',
          code: 'FR',
          bban_format: '10n,11c,2n',
          iban_length: 27,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          branch_code: [9, 14],
          branch_code_regex: '\d{5}',
          national_checksum: [25, 27],
          national_checksum_regex: '\d{2}',
          account_number: [14, 25],
          account_number_regex: '[a-zA-Z0-9]{11}',
          regex: 'FR\d\d\d{10}[a-zA-Z0-9]{11}\d{2}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        GE: {
          name: 'Georgia',
          code: 'GE',
          bban_format: '2c,16n',
          iban_length: 22,
          bank_code: [4, 6],
          bank_code_regex: '[a-zA-Z0-9]{2}',
          account_number: [6, 22],
          account_number_regex: '\d{16}',
          regex: 'GE\d\d[a-zA-Z0-9]{2}\d{16}',
          parts: %w[bank_code account_number],
          },
        DE: {
          name: 'Germany',
          code: 'DE',
          bban_format: '18n',
          iban_length: 22,
          bank_code: [4, 12],
          bank_code_regex: '\d{8}',
          account_number: [12, 22],
          account_number_regex: '\d{10}',
          regex: 'DE\d\d\d{18}',
          parts: %w[bank_code account_number],
          },
        GI: {
          name: 'Gibraltar',
          code: 'GI',
          bban_format: '4a,15c',
          iban_length: 23,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 23],
          account_number_regex: '[a-zA-Z0-9]{15}',
          regex: 'GI\d\d[A-Z]{4}[a-zA-Z0-9]{15}',
          parts: %w[bank_code account_number],
          },
        GR: {
          name: 'Greece',
          code: 'GR',
          bban_format: '7n,16c',
          iban_length: 27,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 11],
          branch_code_regex: '\d{4}',
          account_number: [11, 27],
          account_number_regex: '[a-zA-Z0-9]{16}',
          regex: 'GR\d\d\d{7}[a-zA-Z0-9]{16}',
          parts: %w[bank_code branch_code account_number],
          },
        GL: {
          name: 'Greenland',
          code: 'GL',
          bban_format: '14n',
          iban_length: 18,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          national_checksum: [17, 18],
          national_checksum_regex: '\d{1}',
          account_number: [8, 17],
          account_number_regex: '\d{9}',
          regex: 'GL\d\d\d{14}',
          parts: %w[bank_code checksum account_number],
          },
        GT: {
          name: 'Guatemala',
          code: 'GT',
          bban_format: '4c,20c',
          iban_length: 28,
          bank_code: [4, 8],
          bank_code_regex: '[a-zA-Z0-9]{4}',
          account_number: [12, 28],
          account_number_regex: '[a-zA-Z0-9]{16}',
          account_type: [10, 12],
          account_type_regex: '[a-zA-Z0-9]{2}',
          currency_code: [8, 10],
          currency_code_regex: '[a-zA-Z0-9]{2}',
          regex: 'GT\d\d[a-zA-Z0-9]{4}[a-zA-Z0-9]{20}',
          parts: %w[bank_code account_number account_type currency_code],
          },
        HU: {
          name: 'Hungary',
          code: 'HU',
          bban_format: '24n',
          iban_length: 28,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 11],
          branch_code_regex: '\d{4}',
          national_checksum: [11, 28],
          national_checksum_regex: '\d{17}',
          account_number: [12, 27],
          account_number_regex: '\d{15}',
          regex: 'HU\d\d\d{24}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        IS: {
          name: 'Iceland',
          code: 'IS',
          bban_format: '22n',
          iban_length: 26,
          bank_code: [4, 6],
          bank_code_regex: '\d{2}',
          branch_code: [6, 8],
          branch_code_regex: '\d{2}',
          account_number: [10, 16],
          account_number_regex: '\d{6}',
          account_type: [8, 10],
          account_type_regex: '\d{2}',
          kennitala: [16, 26],
          kennitala_regex: '\d{10}',
          regex: 'IS\d\d\d{22}',
          parts: %w[bank_code branch_code account_number account_type kennitala],
          },
        IQ: {
          name: 'Iraq',
          code: 'IQ',
          bban_format: '4a,15n',
          iban_length: 23,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          branch_code: [8, 11],
          branch_code_regex: '\d{3}',
          account_number: [11, 23],
          account_number_regex: '\d{12}',
          regex: 'IQ\d\d[A-Z]{4}\d{15}',
          parts: %w[bank_code branch_code account_number],
          },
        IE: {
          name: 'Ireland',
          code: 'IE',
          bban_format: '4c,14n',
          iban_length: 22,
          bank_code: [8, 14],
          bank_code_regex: '\d{6}',
          account_number: [14, 22],
          account_number_regex: '\d{8}',
          balance_account_number: [4, 8],
          balance_account_number_regex: '[a-zA-Z0-9]{4}',
          regex: 'IE\d\d[a-zA-Z0-9]{4}\d{14}',
          parts: %w[bank_code account_number balance_account_number],
          },
        IL: {
          name: 'Israel',
          code: 'IL',
          bban_format: '19n',
          iban_length: 23,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 10],
          branch_code_regex: '\d{3}',
          account_number: [10, 23],
          account_number_regex: '\d{13}',
          regex: 'IL\d\d\d{19}',
          parts: %w[bank_code branch_code account_number],
          },
        IT: {
          name: 'Italy',
          code: 'IT',
          bban_format: '1a,10n,12c',
          iban_length: 27,
          bank_code: [5, 10],
          bank_code_regex: '\d{5}',
          branch_code: [10, 15],
          branch_code_regex: '\d{5}',
          national_checksum: [4, 5],
          national_checksum_regex: '[A-Z]{1}',
          account_number: [15, 27],
          account_number_regex: '[a-zA-Z0-9]{12}',
          regex: 'IT\d\d[A-Z]{1}\d{10}[a-zA-Z0-9]{12}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        JO: {
          name: 'Jordan',
          code: 'JO',
          bban_format: '4a,22n',
          iban_length: 30,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          account_number: [12, 30],
          account_number_regex: '\d{18}',
          regex: 'JO\d\d[A-Z]{4}\d{22}',
          parts: %w[bank_code branch_code account_number],
          },
        KZ: {
          name: 'Kazakhstan',
          code: 'KZ',
          bban_format: '3n,13c',
          iban_length: 20,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          account_number: [7, 20],
          account_number_regex: '[a-zA-Z0-9]{13}',
          regex: 'KZ\d\d\d{3}[a-zA-Z0-9]{13}',
          parts: %w[bank_code account_number],
          },
        XK: {
          name: 'Kosovo',
          code: 'XK',
          bban_format: '4n,10n,2n',
          iban_length: 20,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          account_number: [8, 20],
          account_number_regex: '\d{12}',
          regex: 'XK\d\d\d{4}\d{10}\d{2}',
          parts: %w[bank_code account_number],
          },
        KW: {
          name: 'Kuwait',
          code: 'KW',
          bban_format: '4a,22c',
          iban_length: 30,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 30],
          account_number_regex: '[a-zA-Z0-9]{22}',
          regex: 'KW\d\d[A-Z]{4}[a-zA-Z0-9]{22}',
          parts: %w[bank_code account_number],
          },
        LV: {
          name: 'Latvia',
          code: 'LV',
          bban_format: '4a,13c',
          iban_length: 21,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 21],
          account_number_regex: '[a-zA-Z0-9]{13}',
          regex: 'LV\d\d[A-Z]{4}[a-zA-Z0-9]{13}',
          parts: %w[bank_code account_number],
          },
        LB: {
          name: 'Lebanon',
          code: 'LB',
          bban_format: '4n,20c',
          iban_length: 28,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          account_number: [8, 28],
          account_number_regex: '[a-zA-Z0-9]{20}',
          regex: 'LB\d\d\d{4}[a-zA-Z0-9]{20}',
          parts: %w[bank_code account_number],
          },
        LY: {
          name: 'Libya',
          code: 'LY',
          bban_format: '21n',
          iban_length: 25,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 10],
          branch_code_regex: '\d{3}',
          account_number: [10, 25],
          account_number_regex: '\d{15}',
          regex: 'LY\d\d\d{21}',
          parts: %w[bank_code branch_code account_number],
          },
        LI: {
          name: 'Liechtenstein',
          code: 'LI',
          bban_format: '5n,12c',
          iban_length: 21,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          account_number: [9, 21],
          account_number_regex: '[a-zA-Z0-9]{12}',
          regex: 'LI\d\d\d{5}[a-zA-Z0-9]{12}',
          parts: %w[bank_code account_number],
          },
        LT: {
          name: 'Lithuania',
          code: 'LT',
          bban_format: '16n',
          iban_length: 20,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          account_number: [9, 20],
          account_number_regex: '\d{11}',
          regex: 'LT\d\d\d{16}',
          parts: %w[bank_code account_number],
          },
        LU: {
          name: 'Luxembourg',
          code: 'LU',
          bban_format: '3n,13c',
          iban_length: 20,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          account_number: [7, 20],
          account_number_regex: '[a-zA-Z0-9]{13}',
          regex: 'LU\d\d\d{3}[a-zA-Z0-9]{13}',
          parts: %w[bank_code account_number],
          },
        MK: {
          name: 'North Macedonia',
          code: 'MK',
          bban_format: '3n,10c,2n',
          iban_length: 19,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          national_checksum: [17, 19],
          national_checksum_regex: '\d{2}',
          account_number: [7, 17],
          account_number_regex: '[a-zA-Z0-9]{10}',
          regex: 'MK\d\d\d{3}[a-zA-Z0-9]{10}\d{2}',
          parts: %w[bank_code checksum account_number],
          const_global_checksum: '07',
          },
        MT: {
          name: 'Malta',
          code: 'MT',
          bban_format: '4a,5n,18c',
          iban_length: 31,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          branch_code: [8, 13],
          branch_code_regex: '\d{5}',
          account_number: [13, 31],
          account_number_regex: '[a-zA-Z0-9]{18}',
          regex: 'MT\d\d[A-Z]{4}\d{5}[a-zA-Z0-9]{18}',
          parts: %w[bank_code branch_code account_number],
          },
        MR: {
          name: 'Mauritania',
          code: 'MR',
          bban_format: '23n',
          iban_length: 27,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          branch_code: [9, 14],
          branch_code_regex: '\d{5}',
          national_checksum: [25, 27],
          national_checksum_regex: '\d{2}',
          account_number: [14, 25],
          account_number_regex: '\d{11}',
          regex: 'MR\d\d\d{23}',
          parts: %w[bank_code branch_code checksum account_number],
          const_global_checksum: '13',
          },
        MU: {
          name: 'Mauritius',
          code: 'MU',
          bban_format: '4a,19n,3a',
          iban_length: 30,
          bank_code: [4, 10],
          bank_code_regex: '[A-Z][A-Z][A-Z][A-Z]\d\d',
          branch_code: [10, 12],
          branch_code_regex: '\d{2}',
          account_number: [12, 24],
          account_number_regex: '\d{12}',
          currency_code: [27, 30],
          currency_code_regex: '[A-Z]{3}',
          zero: [24, 27],
          zero_regex: '\d{3}',
          regex: 'MU\d\d[A-Z]{4}\d{19}[A-Z]{3}',
          parts: %w[bank_code branch_code account_number currency_code],
          },
        MC: {
          name: 'Monaco',
          code: 'MC',
          bban_format: '10n,11c,2n',
          iban_length: 27,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          branch_code: [9, 14],
          branch_code_regex: '\d{5}',
          national_checksum: [25, 27],
          national_checksum_regex: '\d{2}',
          account_number: [14, 25],
          account_number_regex: '[a-zA-Z0-9]{11}',
          regex: 'MC\d\d\d{10}[a-zA-Z0-9]{11}\d{2}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        MD: {
          name: 'Moldova',
          code: 'MD',
          bban_format: '2c,18c',
          iban_length: 24,
          bank_code: [4, 6],
          bank_code_regex: '[a-zA-Z0-9]{2}',
          account_number: [6, 24],
          account_number_regex: '[a-zA-Z0-9]{18}',
          regex: 'MD\d\d[a-zA-Z0-9]{2}[a-zA-Z0-9]{18}',
          parts: %w[bank_code account_number],
          },
        ME: {
          name: 'Montenegro',
          code: 'ME',
          bban_format: '18n',
          iban_length: 22,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          national_checksum: [20, 22],
          national_checksum_regex: '\d{2}',
          account_number: [7, 20],
          account_number_regex: '\d{13}',
          regex: 'ME\d\d\d{18}',
          parts: %w[bank_code checksum account_number],
          const_global_checksum: '25',
          },
        NL: {
          name: 'Netherlands',
          code: 'NL',
          bban_format: '4a,10n',
          iban_length: 18,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 18],
          account_number_regex: '\d{10}',
          regex: 'NL\d\d[A-Z]{4}\d{10}',
          parts: %w[bank_code account_number],
          },
        NO: {
          name: 'Norway',
          code: 'NO',
          bban_format: '11n',
          iban_length: 15,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          national_checksum: [14, 15],
          national_checksum_regex: '\d{1}',
          account_number: [8, 14],
          account_number_regex: '\d{6}',
          regex: 'NO\d\d\d{11}',
          parts: %w[bank_code checksum account_number],
          },
        PK: {
          name: 'Pakistan',
          code: 'PK',
          bban_format: '4c,16n',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '[a-zA-Z0-9]{4}',
          account_number: [8, 24],
          account_number_regex: '\d{16}',
          regex: 'PK\d\d[a-zA-Z0-9]{4}\d{16}',
          parts: %w[bank_code account_number],
          },
        PS: {
          name: 'Palestinian territories',
          code: 'PS',
          bban_format: '4c,21n',
          iban_length: 29,
          bank_code: [4, 8],
          bank_code_regex: '[a-zA-Z0-9]{4}',
          account_number: [8, 29],
          account_number_regex: '\d{21}',
          regex: 'PS\d\d[a-zA-Z0-9]{4}\d{21}',
          parts: %w[bank_code account_number],
          },
        PL: {
          name: 'Poland',
          code: 'PL',
          bban_format: '24n',
          iban_length: 28,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          branch_code: [7, 11],
          branch_code_regex: '\d{4}',
          national_checksum: [11, 12],
          national_checksum_regex: '\d{1}',
          account_number: [12, 28],
          account_number_regex: '\d{16}',
          regex: 'PL\d\d\d{24}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        PT: {
          name: 'Portugal',
          code: 'PT',
          bban_format: '21n',
          iban_length: 25,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          national_checksum: [23, 25],
          national_checksum_regex: '\d{2}',
          account_number: [12, 23],
          account_number_regex: '\d{11}',
          regex: 'PT\d\d\d{21}',
          parts: %w[bank_code branch_code checksum account_number],
          const_global_checksum: '50',
          },
        QA: {
          name: 'Qatar',
          code: 'QA',
          bban_format: '4a,21c',
          iban_length: 29,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 29],
          account_number_regex: '[a-zA-Z0-9]{21}',
          regex: 'QA\d\d[A-Z]{4}[a-zA-Z0-9]{21}',
          parts: %w[bank_code account_number],
          },
        RO: {
          name: 'Romania',
          code: 'RO',
          bban_format: '4a,16c',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 24],
          account_number_regex: '[a-zA-Z0-9]{16}',
          regex: 'RO\d\d[A-Z]{4}[a-zA-Z0-9]{16}',
          parts: %w[bank_code account_number],
          },
        LC: {
          name: 'Saint Lucia',
          code: 'LC',
          bban_format: '4a,24c',
          iban_length: 32,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          account_number: [8, 32],
          account_number_regex: '[a-zA-Z0-9]{24}',
          regex: 'LC\d\d[A-Z]{4}[a-zA-Z0-9]{24}',
          parts: %w[bank_code account_number],
          },
        SM: {
          name: 'San Marino',
          code: 'SM',
          bban_format: '1a,10n,12c',
          iban_length: 27,
          bank_code: [5, 10],
          bank_code_regex: '\d{5}',
          branch_code: [10, 15],
          branch_code_regex: '\d{5}',
          national_checksum: [4, 5],
          national_checksum_regex: '[A-Z]{1}',
          account_number: [15, 27],
          account_number_regex: '[a-zA-Z0-9]{12}',
          regex: 'SM\d\d[A-Z]{1}\d{10}[a-zA-Z0-9]{12}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        ST: {
          name: 'São Tomé and Príncipe',
          code: 'ST',
          bban_format: '21n',
          iban_length: 25,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          account_number: [12, 25],
          account_number_regex: '\d{13}',
          regex: 'ST\d\d\d{21}',
          parts: %w[bank_code branch_code account_number],
          },
        SA: {
          name: 'Saudi Arabia',
          code: 'SA',
          bban_format: '2n,18c',
          iban_length: 24,
          bank_code: [4, 6],
          bank_code_regex: '\d{2}',
          account_number: [6, 24],
          account_number_regex: '[a-zA-Z0-9]{18}',
          regex: 'SA\d\d\d{2}[a-zA-Z0-9]{18}',
          parts: %w[bank_code account_number],
          },
        RS: {
          name: 'Serbia',
          code: 'RS',
          bban_format: '18n',
          iban_length: 22,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          national_checksum: [20, 22],
          national_checksum_regex: '\d{2}',
          account_number: [7, 20],
          account_number_regex: '\d{13}',
          regex: 'RS\d\d\d{18}',
          parts: %w[bank_code checksum account_number],
          const_global_checksum: '35',
          },
        SC: {
          name: 'Seychelles',
          code: 'SC',
          bban_format: '4a,20n,3a',
          iban_length: 31,
          bank_code: [4, 10],
          bank_code_regex: '[A-Z][A-Z][A-Z][A-Z]\d\d',
          branch_code: [10, 12],
          branch_code_regex: '\d{2}',
          account_number: [12, 28],
          account_number_regex: '\d{16}',
          currency_code: [28, 31],
          currency_code_regex: '[A-Z]{3}',
          regex: 'SC\d\d[A-Z]{4}\d{20}[A-Z]{3}',
          parts: %w[bank_code branch_code account_number currency_code],
          },
        SK: {
          name: 'Slovakia',
          code: 'SK',
          bban_format: '20n',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [12, 14],
          branch_code_regex: '\d{2}',
          account_number: [14, 24],
          account_number_regex: '\d{10}',
          account_prefix: [8, 12],
          account_prefix_regex: '\d{4}',
          regex: 'SK\d\d\d{20}',
          parts: %w[bank_code branch_code account_number account_prefix],
          },
        SI: {
          name: 'Slovenia',
          code: 'SI',
          bban_format: '15n',
          iban_length: 19,
          bank_code: [4, 6],
          bank_code_regex: '\d{2}',
          branch_code: [6, 9],
          branch_code_regex: '\d{3}',
          national_checksum: [17, 19],
          national_checksum_regex: '\d{2}',
          account_number: [9, 17],
          account_number_regex: '\d{8}',
          regex: 'SI\d\d\d{15}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        ES: {
          name: 'Spain',
          code: 'ES',
          bban_format: '20n',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '\d{4}',
          branch_code: [8, 12],
          branch_code_regex: '\d{4}',
          national_checksum: [12, 14],
          national_checksum_regex: '\d{2}',
          account_number: [14, 24],
          account_number_regex: '\d{10}',
          regex: 'ES\d\d\d{20}',
          parts: %w[bank_code branch_code checksum account_number],
          },
        SD: {
          name: 'Sudan',
          code: 'SD',
          bban_format: '14n',
          iban_length: 18,
          bank_code: [4, 6],
          bank_code_regex: '\d{2}',
          account_number: [6, 18],
          account_number_regex: '\d{12}',
          regex: 'SD\d\d\d{14}',
          parts: %w[bank_code account_number],
          },
        SE: {
          name: 'Sweden',
          code: 'SE',
          bban_format: '20n',
          iban_length: 24,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          account_number: [7, 24],
          account_number_regex: '\d{17}',
          regex: 'SE\d\d\d{20}',
          parts: %w[bank_code account_number],
          },
        CH: {
          name: 'Switzerland',
          code: 'CH',
          bban_format: '5n,12c',
          iban_length: 21,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          account_number: [9, 21],
          account_number_regex: '[a-zA-Z0-9]{12}',
          regex: 'CH\d\d\d{5}[a-zA-Z0-9]{12}',
          parts: %w[bank_code account_number],
          },
        TN: {
          name: 'Tunisia',
          code: 'TN',
          bban_format: '20n',
          iban_length: 24,
          bank_code: [4, 6],
          bank_code_regex: '\d{2}',
          branch_code: [6, 9],
          branch_code_regex: '\d{3}',
          national_checksum: [22, 24],
          national_checksum_regex: '\d{2}',
          account_number: [9, 22],
          account_number_regex: '\d{13}',
          regex: 'TN\d\d\d{20}',
          parts: %w[bank_code branch_code checksum account_number],
          const_global_checksum: '59',
          },
        TR: {
          name: 'Turkey',
          code: 'TR',
          bban_format: '5n,17c',
          iban_length: 26,
          bank_code: [4, 9],
          bank_code_regex: '\d{5}',
          account_number: [10, 26],
          account_number_regex: '[a-zA-Z0-9]{16}',
          zero: [9, 10],
          zero_regex: '[a-zA-Z0-9]{1}',
          regex: 'TR\d\d\d{5}[a-zA-Z0-9]{17}',
          parts: %w[bank_code account_number],
          },
        UA: {
          name: 'Ukraine',
          code: 'UA',
          bban_format: '6n,19c',
          iban_length: 29,
          bank_code: [4, 10],
          bank_code_regex: '\d{6}',
          account_number: [10, 29],
          account_number_regex: '[a-zA-Z0-9]{19}',
          regex: 'UA\d\d\d{6}[a-zA-Z0-9]{19}',
          parts: %w[bank_code account_number],
          },
        AE: {
          name: 'United Arab Emirates',
          code: 'AE',
          bban_format: '3n,16n',
          iban_length: 23,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          account_number: [7, 23],
          account_number_regex: '\d{16}',
          regex: 'AE\d\d\d{3}\d{16}',
          parts: %w[bank_code account_number],
          },
        GB: {
          name: 'United Kingdom',
          code: 'GB',
          bban_format: '4a,14n',
          iban_length: 22,
          bank_code: [4, 8],
          bank_code_regex: '[A-Z]{4}',
          branch_code: [8, 14],
          branch_code_regex: '\d{6}',
          account_number: [14, 22],
          account_number_regex: '\d{8}',
          regex: 'GB\d\d[A-Z]{4}\d{14}',
          parts: %w[bank_code branch_code account_number],
          },
        VA: {
          name: 'Vatican City',
          code: 'VA',
          bban_format: '3n,15n',
          iban_length: 22,
          bank_code: [4, 7],
          bank_code_regex: '\d{3}',
          account_number: [7, 22],
          account_number_regex: '\d{15}',
          regex: 'VA\d\d\d{3}\d{15}',
          parts: %w[bank_code account_number],
          },
        VG: {
          name: 'Virgin Islands, British',
          code: 'VG',
          bban_format: '4c,16n',
          iban_length: 24,
          bank_code: [4, 8],
          bank_code_regex: '[a-zA-Z0-9]{4}',
          account_number: [8, 24],
          account_number_regex: '\d{16}',
          regex: 'VG\d\d[a-zA-Z0-9]{4}\d{16}',
          parts: %w[bank_code account_number],
          },
      }
    end
  end
end